/**
 * Market cap data fetcher — reads from a pre-generated JSON cache file.
 * The cache file is generated by running: python3 server/scripts/fetch_mcap.py > server/scripts/mcap_cache.json
 * A background refresh runs every 30 minutes using spawn (detached) to avoid tsx watch killing it.
 */
import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export type McapEntry = {
  marketCap: number;
  sharesOutstanding: number;
};

const CACHE_FILE = path.join(__dirname, "scripts", "mcap_cache.json");
const SCRIPT_FILE = path.join(__dirname, "scripts", "fetch_mcap.py");

let mcapCache: Record<string, McapEntry> = {};
let lastFetchTime = 0;
const CACHE_TTL = 30 * 60 * 1000; // 30 minutes
let refreshInProgress = false;

function readCacheFile(): Record<string, McapEntry> {
  try {
    if (!fs.existsSync(CACHE_FILE)) return {};
    const raw = fs.readFileSync(CACHE_FILE, "utf-8");
    const data = JSON.parse(raw);
    const result: Record<string, McapEntry> = {};
    for (const [ticker, val] of Object.entries(data)) {
      const v = val as { marketCap?: number; sharesOutstanding?: number };
      result[ticker] = {
        marketCap: v.marketCap || 0,
        sharesOutstanding: v.sharesOutstanding || 0,
      };
    }
    return result;
  } catch (e) {
    console.warn("[MCAP] Failed to read cache file:", (e as Error).message);
    return {};
  }
}

function triggerBackgroundRefresh(): void {
  if (refreshInProgress) return;
  refreshInProgress = true;
  console.log("[MCAP] Starting background refresh...");

  const child = spawn("python3", [SCRIPT_FILE], {
    stdio: ["ignore", "pipe", "ignore"],
    detached: true,
  });

  let stdout = "";
  child.stdout.on("data", (chunk: Buffer) => {
    stdout += chunk.toString();
  });

  child.on("close", (code) => {
    refreshInProgress = false;
    if (code === 0 && stdout.length > 10) {
      try {
        JSON.parse(stdout);
        fs.writeFileSync(CACHE_FILE, stdout, "utf-8");
        mcapCache = readCacheFile();
        lastFetchTime = Date.now();
        console.log(`[MCAP] Background refresh complete: ${Object.keys(mcapCache).length} tickers`);
      } catch {
        console.warn("[MCAP] Invalid JSON from refresh script");
      }
    } else {
      console.warn(`[MCAP] Background refresh failed with code ${code}`);
    }
  });

  child.on("error", (err) => {
    refreshInProgress = false;
    console.warn("[MCAP] Background refresh error:", err.message);
  });

  child.unref();
}

export async function getMcapData(): Promise<Record<string, McapEntry>> {
  const now = Date.now();
  const isStale = now - lastFetchTime > CACHE_TTL;

  if (Object.keys(mcapCache).length === 0) {
    mcapCache = readCacheFile();
    if (Object.keys(mcapCache).length > 0) {
      lastFetchTime = now;
      console.log(`[MCAP] Loaded ${Object.keys(mcapCache).length} tickers from cache file`);
    }
  }

  if (isStale) {
    triggerBackgroundRefresh();
  }

  return mcapCache;
}

export function getTickerMcap(ticker: string): McapEntry {
  return mcapCache[ticker] || { marketCap: 0, sharesOutstanding: 0 };
}
