import { describe, expect, it } from "vitest";
import { generateReportTitle, generateReportContent, type ReportData } from "./reportGenerator";

function createMockReportData(): ReportData {
  return {
    generatedAt: "2026-02-22T04:00:00.000Z",
    stocks: [
      {
        ticker: "MSTR",
        company: "Strategy (MicroStrategy)",
        category: "Majors",
        datAsset: "BTC",
        price: 131.05,
        change1d: 1.24,
        change7d: -1.47,
        change30d: -20.0,
        volume: 17530000,
        error: false,
      },
      {
        ticker: "COIN",
        company: "Coinbase Global",
        category: "Majors",
        datAsset: "BTC",
        price: 171.35,
        change1d: 3.26,
        change7d: 5.44,
        change30d: -24.49,
        volume: 13540000,
        error: false,
      },
      {
        ticker: "FORD",
        company: "Forward Industries",
        category: "Majors",
        datAsset: "SOL",
        price: 0,
        change1d: 0,
        change7d: 0,
        change30d: 0,
        volume: 0,
        error: true,
      },
      {
        ticker: "ZBAI",
        company: "ATIF Holdings",
        category: "Alts",
        datAsset: "DOGE",
        price: 6.53,
        change1d: -1.06,
        change7d: -3.97,
        change30d: -4.53,
        volume: 230,
        error: false,
      },
    ],
    crypto: [
      {
        symbol: "BTC",
        name: "Bitcoin",
        price: 96500,
        change1d: -0.5,
        change7d: -2.1,
        change30d: -5.3,
        volume: 25000000000,
        error: false,
      },
      {
        symbol: "ETH",
        name: "Ethereum",
        price: 2700,
        change1d: -1.2,
        change7d: -4.5,
        change30d: -10.1,
        volume: 12000000000,
        error: false,
      },
    ],
    summary: {
      totalCompanies: 4,
      majorsCount: 3,
      altsCount: 1,
      avgChange1d: 1.15,
      topGainer: { ticker: "COIN", change1d: 3.26 },
      topLoser: { ticker: "ZBAI", change1d: -1.06 },
      gainersCount: 2,
      losersCount: 1,
      cryptoAvgChange1d: -0.85,
    },
  };
}

describe("generateReportTitle", () => {
  it("generates a title with date and avg change", () => {
    const data = createMockReportData();
    const title = generateReportTitle(data);

    expect(title).toContain("DAT Daily Report");
    expect(title).toContain("Feb");
    expect(title).toContain("2026");
    expect(title).toContain("1.15%");
  });

  it("uses up arrow for positive avg change", () => {
    const data = createMockReportData();
    data.summary.avgChange1d = 2.5;
    const title = generateReportTitle(data);
    expect(title).toContain("↑");
  });

  it("uses down arrow for negative avg change", () => {
    const data = createMockReportData();
    data.summary.avgChange1d = -1.5;
    const title = generateReportTitle(data);
    expect(title).toContain("↓");
  });
});

describe("generateReportContent", () => {
  it("includes market overview section", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    expect(content).toContain("MARKET OVERVIEW");
    expect(content).toContain("Companies Tracked: 4");
    expect(content).toContain("3 Majors");
    expect(content).toContain("1 Alts");
  });

  it("includes top gainers and losers", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    expect(content).toContain("TOP 5 GAINERS");
    expect(content).toContain("TOP 5 LOSERS");
    expect(content).toContain("COIN");
    expect(content).toContain("ZBAI");
  });

  it("includes majors and alts sections", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    expect(content).toContain("MAJORS");
    expect(content).toContain("ALTS");
    expect(content).toContain("MSTR");
  });

  it("includes crypto section", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    expect(content).toContain("CRYPTO ASSETS");
    expect(content).toContain("BTC");
    expect(content).toContain("ETH");
    expect(content).toContain("Bitcoin");
  });

  it("shows N/A for errored stocks", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    // FORD has error: true, should show N/A
    const lines = content.split("\n");
    const fordLine = lines.find(l => l.includes("FORD"));
    expect(fordLine).toBeDefined();
    expect(fordLine).toContain("N/A");
  });

  it("includes generation footer", () => {
    const data = createMockReportData();
    const content = generateReportContent(data);

    expect(content).toContain("Generated by DAT Tracker");
  });
});
